image:
  repository: ''
  pullPolicy: IfNotPresent
  tag: ''
serviceAccount:
  create: false
  name: ''
service:
  enabled: true
  type: ClusterIP
  ports:
  - number: 4000
    targetPort: 4000
    name: http
livenessProbe:
  httpGet:
    path: /health/liveliness
    port: 4000
  initialDelaySeconds: 0
  timeoutSeconds: 10
  periodSeconds: 15
  successThreshold: 1
  failureThreshold: 3
readinessProbe:
  httpGet:
    path: /health/readiness
    port: 4000
  initialDelaySeconds: 0
  timeoutSeconds: 10
  periodSeconds: 15
  successThreshold: 1
  failureThreshold: 3
startupProbe:
  httpGet:
    path: /health/liveliness
    port: 4000
  initialDelaySeconds: 20
  timeoutSeconds: 10
  periodSeconds: 10
  failureThreshold: 30
command:
  - "--config"
  - "/app/config.yaml"
  - "--port"
  - "4000"
  - "--num_workers"
  - "4"
volumeMounts:
  - name: config-volume
    mountPath: /app/config.yaml
    subPath: config.yaml
    readOnly: true
volumes:
  - name: config-volume
    configMap:
      name: innovation-litellm-config
configMap:
  name: innovation-litellm-config
  data:
    config.yaml: |
      general_settings:
        master_key: os.environ/LITELLM_MASTER_KEY
        database_url: os.environ/DATABASE_URL
        store_model_in_db: true
      litellm_settings:
        drop_params: true
        set_verbose: false
        store_audit_logs: true
env:
  APP_NAME: innovation-litellm
  OPENAI_API_KEY: ""
  OPENAI_BASE_URL: ""
  COHERE_API_KEY: ""
  OR_SITE_URL: ""
  OR_APP_NAME: "LiteLLM Example app"
  OR_API_KEY: ""
  AZURE_API_BASE: ""
  AZURE_API_VERSION: ""
  AZURE_API_KEY: ""
  REPLICATE_API_KEY: ""
  REPLICATE_API_TOKEN: ""
  ANTHROPIC_API_KEY: ""
  INFISICAL_TOKEN: ""
  NOVITA_API_KEY: ""
  INFINITY_API_KEY: ""
  STORE_MODEL_IN_DB: "True"
