image:
  repository: ''
  pullPolicy: IfNotPresent
  tag: ''
serviceAccount:
  create: false
  name: ''
service:
  enabled: true
  type: ClusterIP
  ports:
  - number: 4000
    targetPort: 4000
    name: http
livenessProbe:
  httpGet:
    path: /health/liveliness
    port: 4000
  initialDelaySeconds: 0
  timeoutSeconds: 10
  periodSeconds: 15
  successThreshold: 1
  failureThreshold: 3
readinessProbe:
  httpGet:
    path: /health/readiness
    port: 4000
  initialDelaySeconds: 0
  timeoutSeconds: 10
  periodSeconds: 15
  successThreshold: 1
  failureThreshold: 3
startupProbe:
  httpGet:
    path: /health/liveliness
    port: 4000
  initialDelaySeconds: 20
  timeoutSeconds: 10
  periodSeconds: 10
  failureThreshold: 30
env:
  APP_NAME: stm-litellm
  NO_DOCS: "true"
  NO_REDOC: "true"
  OPENAI_API_KEY: ""
  OPENAI_BASE_URL: ""
  COHERE_API_KEY: ""
  OR_SITE_URL: ""
  OR_APP_NAME: "LiteLLM Example app"
  OR_API_KEY: ""
  AZURE_API_BASE: ""
  AZURE_API_VERSION: ""
  AZURE_API_KEY: ""
  REPLICATE_API_KEY: ""
  REPLICATE_API_TOKEN: ""
  ANTHROPIC_API_KEY: ""
  INFISICAL_TOKEN: ""
  NOVITA_API_KEY: ""
  INFINITY_API_KEY: ""
  STORE_MODEL_IN_DB: "True"
